blog/urls.py
# Create your tests here.
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
 
app_name = 'blog'  ## 命名空间
urlpatterns = [
    path('index', views.IndexView.as_view(), name='index'),
    path('', views.InitView.as_view(), name='init'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'), # 跳转到文章详情
 #   path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
	path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
	
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    #path('tags/<int:pk>/', views.tag, name='tag'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
	
    path('about', views.AboutView.as_view(), name='about'),
	
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('blog.urls')),
	path('', include('comments.urls')),
]

blog/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone 
from django.urls import reverse
import markdown
from django.utils.html import strip_tags

 
class Category(models.Model):
    """
    django 要求模型必须继承 models.Model 类。
    Category 只需要一个简单的分类名 name 就可以了。
    CharField 指定了分类名 name 的数据类型，CharField 是字符型，
    CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
    当然 django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
    django 内置的全部类型可查看文档：
    https://docs.djangoproject.com/en/2.2/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100)
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name
		
		
		
 
class Tag(models.Model):
    """
    标签 Tag 也比较简单，和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name = models.CharField(max_length=100)
    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name
 
class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """
 
    # 文章标题
    title = models.CharField('标题',max_length=70)
 
    # 文章正文，我们使用了 TextField。
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    body = models.TextField('正文')
 
    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    modified_time = models.DateTimeField('修改时间')
 
    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField('摘要', max_length=200, blank=True)
 
    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一
    # 对多的关联关系。且自 django 2.0 以后，ForeignKey 必须传入一个 on_delete 参数用来指定当关联的
    # 数据被删除时，被关联的数据的行为，我们这里假定当某个分类被删除时，该分类下全部文章也同时被删除，因此     # 使用 models.CASCADE 参数，意为级联删除。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 
    # ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
    # https://docs.djangoproject.com/en/2.2/topics/db/models/#relationships
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)
 
    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 
    # django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 
    # Category 类似。
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)
    
	
    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0, editable=False)

	# 新增文章的图片
    pic = models.ImageField(upload_to='pic/%Y%m%d/', blank=True)
	
    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name  ## 中文没有复数
        ordering = ['-created_time']

    def increase_views(self): # 阅读量增1
        self.views += 1
        self.save(update_fields=['views'])
		
		
    def save(self, *args, **kwargs):   
        self.modified_time = timezone.now() ## 修改时间 自动更新为现在的时刻
		
        # 自动生成摘要
		# 首先实例化一个 Markdown 类，用于渲染 body 的文本。
        # 由于摘要并不需要生成文章目录，所以去掉了目录拓展。
        md = markdown.Markdown(extensions=[
             'markdown.extensions.extra',
             'markdown.extensions.codehilite',
         ])
 
        # 先将 Markdown 文本渲染成 HTML 文本
        # strip_tags 去掉 HTML 文本的全部 HTML 标签
        # 从文本摘取前 54 个字符赋给 excerpt
        self.excerpt = strip_tags(md.convert(self.body))[:54]		
		
        super().save(*args, **kwargs)

    def __str__(self):
	    return self.title
		
    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

comments/models.py
from django.db import models

# Create your models here.

from django.utils import timezone
 
 
class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    email = models.EmailField('邮箱')
    url = models.URLField('网址', blank=True)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey('blog.Post', verbose_name='文章', on_delete=models.CASCADE)
 
    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
import markdown
import re
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
# 引入 Category 类
from .models import Post, Category, Tag
from django.views.generic import ListView, DetailView # 类视图
from pure_pagination.mixins import PaginationMixin 
from itertools import chain # 返回多个值用

class InitView(PaginationMixin, ListView):
    model = Post
    template_name = 'blog/base_pic.html'
    context_object_name = 'post_list' 
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 20


class IndexView(PaginationMixin, ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list' 
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 20

class BaseView(PaginationMixin, ListView):
    model = Post
    template_name = 'blog/base.html'
    context_object_name = 'post_list' 
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 20	


class AboutView(BaseView):
    model = Post
    template_name = 'blog/about.html'
    context_object_name = 'post_list' 


	
class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'
 
    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)
 
        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()
 
        # 视图必须返回一个 HttpResponse 对象
        return response
 
    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super().get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            # 记得在顶部引入 TocExtension 和 slugify
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.body)
 
        m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
        post.toc = m.group(1) if m is not None else ''
 
        return post

'''		
# 点击侧边栏归档	
def archive(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})
'''
	
class ArchiveView(IndexView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    def get_queryset(self):   # 多参数在 kwargs 中
        year = self.kwargs['year']
        month = self.kwargs['month']
        return super().get_queryset().filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')

    def get_context_data(self, **kwargs):    # 传到html更多的上下文，即内容
        context = super().get_context_data(**kwargs)
        year = self.kwargs['year']
        month = self.kwargs['month']
        context['archive_year'] = year;
        context['archive_month'] = month;
        return context										

		
		
	
# 点击侧边栏分类	
class CategoryView(IndexView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)



#def tag(request, pk):
#    # 记得在开始部分导入 Tag 类
#    paginate_by = 10
#    t = get_object_or_404(Tag, pk=pk)
#    post_list = Post.objects.filter(tags=t).order_by('-created_time')
#    return render(request, 'blog/index.html', context={'post_list': post_list})
class TagView(IndexView):
    def get_queryset(self):
        t = get_object_or_404(Tag, pk=self.kwargs.get("pk"))

        return super().get_queryset().filter(tags=t)	

    def get_context_data(self, **kwargs):    # 传到html更多的上下文，即内容
        context = super().get_context_data(**kwargs)
        t = get_object_or_404(Tag, pk=self.kwargs.get("pk"))
        tag_name = t;
        context['tag_name'] = tag_name;
        return context

templates/blog/base_pic.html
{% load static %}
{% load blog_extras %}

<!doctype html>
<html lang="zh_Hans_CN" prefix="og: http://ogp.me/ns#">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>个人的生活分享 浮生</title>
  <link rel="icon" type="image/x-icon" href="{% static 'blog/images/favicon.ico' %}">
  <link rel="apple-touch-icon" href="{% static 'blog/images/favicon.ico' %}">
  <link rel="alternate" type="application/atom+xml" title="BlueSkyCC&#39;s Blog atom feed" href="/feed.xml">
  <meta name="description" content="欲淡则心虚，心虚则气清，气清则理明。">
  <meta property="og:site_name" content="BlueSkyCC">
  <meta property="og:type" content="website">
  <meta property="og:title" content="Home">
  <meta property="og:description" content="欲淡则心虚，心虚则气清，气清则理明。">
  <meta property="og:url" content="http://www.blueskycc.com/">
  
  <meta property="og:image" content="{% static 'blog/images/favicon.png' %}">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:image" content="{% static 'blog/images/favicon.png' %}">
  
  <meta name="twitter:creator" content="#">
  <meta name="twitter:site" content="#">
  
  <link rel="canonical" href="http://www.blueskycc.com/">
  
  <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
  
	<link rel="stylesheet" href="{% static 'blog/css/font-awesome.min.css' %}">
	<link href="{% static 'blog/css/df192689c1114f44a80bb778586c412d.css' %}" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="{% static 'blog/css/flog.css' %}">

<meta name="google-site-verification" content="h8jxTRuS6ULFwI6WDoBx0H-7GSBn8vvXSrgX08TrYYc" />
<!--[if lt IE 9]>
    <script src="../static/js/html5shiv.min.js"></script>
<![endif]-->
<script src="{% static 'blog/js/jquery.min.js' %}" crossorgin="anonymous"></script>
<script src="{% static 'blog/js/moment-with-locales.min.js' %}"></script>
<script> 
moment.locale("en");
function flask_moment_render(elem) {
    $(elem).text(eval('moment("' + $(elem).data('timestamp') + '").' + $(elem).data('format') + ';'));
    $(elem).removeClass('flask-moment').show();
}
function flask_moment_render_all() {
    $('.flask-moment').each(function() {
        flask_moment_render(this);
        if ($(this).data('refresh')) {
            (function(elem, interval) { setInterval(function() { flask_moment_render(elem) }, interval); })(this, $(this).data('refresh'));
        }
    })
}
$(document).ready(function() {
    flask_moment_render_all();
});
</script>

<script>
moment.locale("zh-cn");
</script>


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="{% static 'blog/js/3424671173e0429daef0d9912310df9c.js' %}"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
    dataLayer.push(arguments);
  }
  gtag('js', new Date());

  gtag('config', 'UA-138226928-1');

</script>
  <style>:root {--primary-color: #346FAB;}</style>
</head>
<body>


  

  
  
  
<!-- 导航栏 -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark" data-aos="fade-in">
<a class="navbar-brand" href="/">
<img src="{% static 'blog/picture/favicon.png' %}" width="40" height="40" class="d-inline-block" alt="">
<span class="heading">BlueSkyCC</span></a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse align-items-center justify-content-between" id="navbarNavAltMarkup">
	<div class="navbar-nav">
	<a href="{% url 'blog:index' %}" class="nav-item nav-link">首页</a>  
	<a href="#" class="nav-item nav-link">项目</a>
	<a href="#" class="nav-item nav-link">归档</a>
	<a href="{% url 'blog:about' %}" class="nav-item nav-link">关于</a>
	</div>
  
	<form class="form-inline my-2 my-lg-0" action="/search">
		<input class="form-control mr-sm-2" type="search" name="search" aria-label="Search" required>
		<button class="btn btn-dark my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
	</form>
</div>
</nav>
<!-- 导航栏 --> 
  
<!-- 封面 --> 
<div class="cover float-section text-light lazy" data-bg="url('{% static 'blog/images/1.jpg' %}')" 
data-was-processed="true" style="background-image: url({% static 'blog/images/1.jpg' %});">
  <div class="mx-auto my-auto">
    <div class="bio">
      <img class="avatar" src="{% static 'blog/picture/favicon.png' %}" alt="BlueSkyCC's Blog">
      <h1 class="display-3 heading">BlueSkyCC</h1>
      <p class="lead site-des">欲淡则心虚，心虚则气清，气清则理明。</p>
    </div>
    <div class="links lead">
      <a href="javascript:void(0)" class="btn btn-outline-light" onclick="dismissCover()">博客</a>
      <a href="{% url 'blog:about' %}" class="btn btn-outline-light">关于</a>
    </div>
  </div>
</div>
<!-- 封面 --> 
  

  
  
  
  
  
  
  
  
  

<!-- beijing --> 
<section class="container-fluid page-head lazy" data-aos="fade-in" 
style="background-image:url({% static 'blog/images/1.jpg' %});"
>
    <div class="shade"></div>
    
<div class="blog-info mx-auto">
  
  <a href="/" class="blog-head-logo">
    <img class="avatar" src="{% static 'blog/picture/favicon.png' %}" alt="BlueSkyCC&#39;s Blog">
  </a>
  
  <h1 class="heading">
    BlueSkyCC
  </h1>
</div>

</section>
  
  
  
<section class="main" id="main">
<div class="container">
<div class="row">
	  
	  
<!-- 文章目录 -->	  
<div class="col-12 col-lg-8 px-lg-5 center-box page-links" data-aos="fade-up">
 {% for post in post_list %} 
    <div class="post-info d-flex align-items-center justify-content-between" data-type="article">
    <div flex="1">
    <div class="post-meta">
		<span class="post-date"><a href="#"><time class="entry-date"
		datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
		<a class="post-cat" href="#"><i class="fa fa-folder-open"></i>{{ post.category.name }}</a>
    </div>
      <div class="post-item-content">
        <a href="{{ post.get_absolute_url }}">
          <h3 class="post-item-title">{{ post.title }}</h3>
        </a>
      </div>
    </div>
   
	  	  {% if post.pic %}
	   <div class="post-item-image">
        <a href="{{ post.pic.url }}">
          <figure class="lazy" data-bg="url({{ post.pic.url }})"></figure>
        </a>
      </div>
	  {% endif %}
  </div>
	{% empty %}
		<div class="no-post">暂时还没有发布的文章！</div>
	{% endfor %}

	{% if is_paginated %}
	<div class="is_paginated d-flex justify-content-between">
	  
	  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" rel="prev" 
	  {% if page_obj.has_previous %}
		style="visibility: visible;" >
		<i class="fa fa-fw fa-angle-left"></i>上一页{% endif %}
	  </a>
	  
	  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" rel="next" 
	  {% if page_obj.has_next %}
		style="visibility: visible;" >
		下一页 <i class="fa fa-fw fa-angle-right"></i>{% endif %}
	  </a>
	</div>
	{% endif %}	
</div>
<!-- 文章目录 -->


<!-- 侧边栏 -->
<div class="col-12 col-lg-4" data-aos="fade-left">      

<div class="right-section">
  <h2><i class="fa fa-list"></i> 分类 </h2>
  <hr>
  <ul class="cat-list">
	{% show_categories %}
  </ul>
</div>

<div class="right-section">
  <h2><i class="fa fa-tags"></i> 标签</h2>
  <hr>
  <div class="mt-4" id="tag-cloud">
    {% show_tags %}  
  </div>
</div>

<div class="right-section">
  <h2><i class="fa fa-list"></i> 归档 </h2>
  <hr>
  <ul class="cat-list">
    {% show_archives %}  
 </div>




<div class="right-section">
  <h2><i class="fa fa-link"></i> 推荐</h2>
  <hr>
  <ul class="mt-4 page-links cat-list" id="friends">
    
    <li><a href="https://frostming.com/" target="_blank">Frog's Blog</a></li>
  </ul>
</div>
</div>
<!-- 侧边栏 -->

</div>
</div>
</section> 

<footer class="footer text-center page-links">
    <ul class="social-links">
  
  <li>
    <a href="https://github.com/CongWh" target="_blank" title="GitHub">
      
        
      
      <i class="fa fa-fw fa-github"></i>
    </a>
  </li>
  
  <li>
    <a href="#" target="_blank" title="Twitter">
      
        
      
      <i class="fa fa-fw fa-twitter"></i>
    </a>
  </li>
  
  <li>
    <a href="#" target="_blank" title="知乎">
      
        
      
      <i class="iconfont icon-zhihu"></i>
    </a>
  </li>
  
  <li>
    <a href="#" target="_blank" title="Email">
      
        
      
      <i class="fa fa-fw fa-envelope"></i>
    </a>
  </li>
  
  <li><a href="/feed.xml" title="RSS"><i class="fa fa-fw fa-rss"></i></a></li>
</ul>
    <ul class="copyright">
      <li>Powered by <a href="#" target="_blank">Django</a></li>
      <li>&copy;2020-2023<i class="fa fa-heart mx-2" style="color: var(--primary-color)"></i><a href="http://www.blueskycc.cn">BlueSkyCC</a></li>
      
<div style="width:300px;margin:0 auto; padding:20px 0;">
	<a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=42010702000549" 
	style="display:inline-block;text-decoration:none;height:20px;line-height:20px;">
	<img src="" style="float:left;"/>
	<p style="float:left;height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;
	">鄂公网安备 42010702000549号</p></a>
</div>
      
    </ul>
</footer>  





















<script src="{% static 'blog/js/popper.min.js' %}" crossorgin="anonymous"></script>
<script src="{% static 'blog/js/bootstrap.min.js' %}" crossorgin="anonymous"></script>
<script>
  function async (u, c) {
    var d = document,
      t = 'script',
      o = d.createElement(t),
      s = d.getElementsByTagName(t)[0];
    o.src = u;
    if (c) {
      o.addEventListener('load', function (e) {
        c(null, e);
      }, false);
    }
    s.parentNode.insertBefore(o, s);
  }
  // Set the options to make LazyLoad self-initialize
  window.lazyLoadOptions = {
    elements_selector: ".lazy",
    // ... more custom settings?
  };

</script>

<script type="text/javascript" src="{% static 'blog/js/flog.js' %}"></script>
<script async src="{% static 'blog/js/lazyload.min.js' %}"></script>
<script async src="{% static 'blog/js/busuanzi.pure.mini.js' %}"></script>
  
  
<script type="text/javascript">
  if ($('#tag-cloud').length !== 0) {
    async ('/static/js/color-hash.js', function () {
      var colorHash = new ColorHash({
        saturation: 0.5
      });
      $('#tag-cloud > a').each(function (i, e) {
        e.style["background-color"] = colorHash.hex(e.innerHTML.trim());
      });
    })
  }
  var dismissCover = function () {
    var headerHeight = document.getElementsByClassName('page-head')[0].clientHeight;
    $('.cover').animate({
      height: headerHeight,
      opacity: 0
    }, 400, function () {
      $(this).addClass('invisible');
    });
  };
  $(window).on('scroll', dismissCover);
  $(function () {
    if (window.location.search !== '') {
      dismissCover();
    }
  })

</script>

</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% load comments_extras %} 
{% load static %}
{% load blog_extras %}


{% block main %}



<!-- beijing --> 

<section class="container-fluid page-head lazy" data-aos="fade-in" {% if post.pic %}
style="background-image:url({{ post.pic.url }});"
{% else %}
style="background-image:url({% static 'blog/images/1.jpg' %});"
{% endif %}
>
<div class="shade"></div>

<a id="totop" title="Return to the top" class="visible" href="javascript:void(0)">
	<i class="fa fa-fw fa-arrow-up">

	</i>
</a>
<!-- -->
</section>


<section class="main" id="main">
<div class="container">
<div class="row">
<div class="col-12 col-lg-9 px-lg-5 center-box page-links" data-aos="fade-up">
<article class="post post-{{ post.pk }}">
  <div class="d-lg-flex justify-content-between align-items-center">
    <div class="post-meta">
      <time datetime="{{ post.created_time }}">{{ post.created_time }}</time>

      <span itemprop="author" itemscope itemtype="http://schema.org/Person">
        <span class="post-author" itemprop="name">{{ post.author }}</span>
      </span>&nbsp;
	  <span class="post-category">{{ post.category.name }}</span>&nbsp;
	  <span class="views-count">{{ post.views }} 阅读</span>&nbsp;
      <span itemprop="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
    </div>
  </div>
<br>
 <!-- <header class="entry-header">-->
    <h1 class="entry-title" itemprop="headline">{{ post.title }}</h1>

 <!-- </header> -->
  <div class="entry-content clearfix">
    {{ post.body|safe }}  <!-- safe过滤器，使得markdown语法正常显示 -->
  </div>
</article>
</div>

<!-- 目录 -->
<div class="col-12 col-lg-3" data-aos="fade-left">
<div class="post-toc sticky-top">

<div class="toc-head">目录</div>
<div class="list-group" id="table-of-content">
{% block toc %}
{% if post.toc %}
  <div class="toc">
	<ul>
	  {{ post.toc|safe }}
	</ul>
  </div>

{% endif %}
{% endblock toc %}
</div>
</div>
</div>



</div>


<!-- 评论区 --> 
<section class="comment-area" id="comment-area">
<hr>
<h3>发表评论</h3>
{% show_comment_form post %}
<div class="comment-list-panel">
    {% show_comments post %}
</div>
</section>
<!-- 评论区 --> 



</div>
</div>
</section>

{% endblock main %}